# Generated by Django 5.2.4 on 2025-07-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='room',
        ),
        migrations.AddField(
            model_name='guest',
            name='room_number',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite')], default='Single', max_length=50),
        ),
    ]
