# Generated by Django 5.2.4 on 2025-07-10 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_reservation_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='room_number',
        ),
        migrations.AddField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room'),
        ),
    ]
