# Generated by Django 5.2.4 on 2025-07-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_guest_room_number_guest_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
