# Generated by Django 5.2.4 on 2025-07-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_reservation_room_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinandout',
            name='action',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3),
        ),
        migrations.AlterField(
            model_name='guest',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(default='Single', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Checked-in', 'Checked-in'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Dirty', 'Dirty'), ('Out of Order', 'Out of Order')], default='Vacant', max_length=20),
        ),
    ]
